scrape_configs:
  - job_name: 'orchestrate'
    scrape_interval: 1s
    metrics_path: '/metrics'
    static_configs:
      - targets: [
          'tx-sender:8082',
          'tx-listener:8082',
          'chain-registry:8082',
          'api:8082',
          'key-manager:8082',
      ]
