linters-settings:
  govet:
    check-shadowing: true
    settings:
      printf:
        funcs:
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 10
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 5
    min-occurrences: 2
  depguard:
    list-type: blacklist
    packages:
      # logging is allowed only by logutils.Log, logrus
      # is allowed to use only in logutils package
      - github.com/sirupsen/logrus
  misspell:
    locale: US
  lll:
    line-length: 140
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - wrapperFunc

linters:
  enable:
    - goconst
    - goimports
    - gocritic
    - golint
    - interfacer
    - maligned
    - misspell
    - stylecheck
    - unconvert
    - unparam

issues:
  max-same-issues: 10

run:
  deadline: 20m
  skip-dirs:
    - .gocache
    - /build
    - /public
    - mock
    - /scripts
    - /vendor
  skip-files:
    - ".*\\.pb(\\.gw)?\\.go$"
    - pkg/toolkit/app/http/handler/dashboard/genstatic/gen.go
    - pkg/toolkit/app/http/handler/swagger/genstatic/gen.go
