version: "3.7"

x-default-variables: &default-variables
  API_URL: ${API_URL-http://api:8081}
  API_METRICS_URL: ${API_METRICS_URL-http://api:8082}
  LOG_LEVEL: ${LOG_LEVEL-info}
  LOG_FORMAT: ${LOG_FORMAT-}
  MULTI_TENANCY_ENABLED: ${MULTI_TENANCY_ENABLED-}
  AUTH_API_KEY: ${AUTH_API_KEY-}
  AUTH_JWT_ISSUER_URL: ${AUTH_JWT_ISSUER_URL-}
  AUTH_JWT_AUDIENCE: ${AUTH_JWT_AUDIENCE-}
  AUTH_JWT_ORCHESTRATE_CLAIMS: ${AUTH_JWT_ORCHESTRATE_CLAIMS-}
  KAFKA_URL: ${KAFKA_URL-kafka:29092}
  KAFKA_SASL_ENABLED: ${KAFKA_SASL_ENABLED-false}
  KAFKA_SASL_MECHANISM: ${KAFKA_SASL_MECHANISM-PLAIN}
  KAFKA_SASL_USER: ${KAFKA_SASL_USER-}
  KAFKA_SASL_PASSWORD: ${KAFKA_SASL_PASSWORD-}
  KAFKA_TLS_ENABLED: ${KAFKA_TLS_ENABLED-false}
  KAFKA_TLS_INSECURE_SKIP_VERIFY: ${KAFKA_TLS_INSECURE_SKIP_VERIFY-false}
  TOPIC_TX_RECOVER: ${TOPIC_TX_RECOVER-}
  TOPIC_TX_DECODED: ${TOPIC_TX_DECODED-}


services:
  stress:
    image: golang:1.16.9
    entrypoint: /bin/test
    networks:
      - orchestrate
    tty: true
    environment:
      <<: *default-variables
      ARTIFACTS_PATH: "/artifacts"
      STRESS_CONCURRENCY: "15"
      STRESS_ITERATIONS: "100"
      STRESS_TIMEOUT: "10m"
      TEST_GLOBAL_DATA: ${TEST_GLOBAL_DATA-}
      KAFKA_CONSUMER_GROUP_NAME: ${KAFKA_CONSUMER_GROUP_NAME-stress}
    restart: "no"
    command: stress
    volumes:
      - ./build/bin/test:/bin/test
      - ./tests/artifacts:/artifacts

networks:
  orchestrate:
    external:
      name: orchestrate
