version: 2.1

orbs:
  go: circleci/go@1.5.0

commands:
  prepare_golang:
    description: "Checkout, install all packages and handle cache"
    steps:
      - checkout
      - go/mod-download-cached
  prepare_docker:
    description: "Docker login"
    steps:
      - run:
          name: Docker login
          command: |
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin $DOCKER_REGISTRY

  prepare_e2e:
    description: "Orchestrate e2e environment"
    steps:
      - run:
          name: Build test binary
          command: make gobuild-e2e
      - run:
          name: Setup QA environment
          command: |
            echo 'export API_URL=https://qa.orchestrate.ops.consensys.net' >> $BASH_ENV
            echo 'export KAFKA_URL=kafka-qa-0.kafka.ops.consensys.net:9094' >> $BASH_ENV
            echo 'export KAFKA_SASL_ENABLED=true' >> $BASH_ENV
            echo 'export KAFKA_SASL_MECHANISM=PLAIN' >> $BASH_ENV
            echo 'export KAFKA_SASL_USER=${QA_KAFKA_SASL_USER}' >> $BASH_ENV
            echo 'export KAFKA_SASL_PASSWORD=${QA_KAFKA_SASL_PASSWORD}' >> $BASH_ENV
            echo 'export TOPIC_TX_SENDER=qa-tx-sender' >> $BASH_ENV
            echo 'export TOPIC_TX_RECOVER=qa-tx-recover' >> $BASH_ENV
            echo 'export TOPIC_TX_DECODED=qa-tx-decoded' >> $BASH_ENV
            echo 'export MULTI_TENANCY_ENABLED=true' >> $BASH_ENV
            echo 'export AUTH_API_KEY=${QA_AUTH_API_KEY}' >> $BASH_ENV
            echo 'export AUTH_JWT_CLAIMS_NAMESPACE=orchestrate.namespace' >> $BASH_ENV 
            echo 'export AUTH_JWT_CERTIFICATE=${QA_AUTH_JWT_CERTIFICATE}' >> $BASH_ENV
            echo 'export AUTH_JWT_PRIVATE_KEY=${QA_AUTH_JWT_PRIVATE_KEY}' >> $BASH_ENV
            echo 'export TEST_GLOBAL_DATA=${QA_TEST_GLOBAL_DATA}' >> $BASH_ENV

  docker_build_e2e_dev:
    description: "Build Orchestrate E2E"
    steps:
      - run:
          name: Build Orchestrate E2E
          command: >-
            DOCKER_BUILDKIT=1 docker build
            --label org.label-schema.schema-version="1.0.0-rc1"
            --label org.label-schema.build-date=`date -u +"%Y-%m-%dT%H:%M:%SZ"`
            --label org.label-schema.name="${CIRCLE_PROJECT_REPONAME}-e2e"
            --label org.label-schema.version="branch"
            --label org.label-schema.url="https://docs.orchestrate.pegasys.tech"
            --label org.label-schema.vcs-url="${CIRCLE_REPOSITORY_URL}"
            --label org.label-schema.vcs-ref="${CIRCLE_SHA1:0:7}"
            --label org.label-schema.vendor="PegaSys"
            -f ./Dockerfile.e2e
            -q
            -t ${DOCKER_REGISTRY_DEV_REPO}/orchestrate-e2e:${CIRCLE_SHA1:0:7} .

  docker_build_dev:
    description: "Build Orchestrate"
    steps:
      - run:
          name: Build Orchestrate
          command: >-
            DOCKER_BUILDKIT=1 docker build
            --label org.label-schema.schema-version="1.0.0-rc1"
            --label org.label-schema.build-date=`date -u +"%Y-%m-%dT%H:%M:%SZ"`
            --label org.label-schema.name="${CIRCLE_PROJECT_REPONAME}"
            --label org.label-schema.version="branch"
            --label org.label-schema.url="https://docs.orchestrate.pegasys.tech"
            --label org.label-schema.vcs-url="${CIRCLE_REPOSITORY_URL}"
            --label org.label-schema.vcs-ref="${CIRCLE_SHA1:0:7}"
            --label org.label-schema.vendor="PegaSys"
            -q
            -t ${DOCKER_REGISTRY_DEV_REPO}/orchestrate:${CIRCLE_SHA1:0:7} .

jobs:
  lint:
    executor:
      name: go/default
      tag: '1.15.7'
    steps:
      - prepare_golang
      - run:
          name: Check lints
          command: |
            make lint-tools
            make lint-ci

  gobuild:
    executor:
      name: go/default
      tag: '1.15.7'
    steps:
      - prepare_golang
      - run:
          name: Build
          command: make gobuild

  test:
    docker:
      - image: cimg/go:1.15.7
      - image: postgres:13.1-alpine
        environment:
          POSTGRES_PASSWORD: "postgres"
          DB_HOST: "postgres"
    resource_class: xlarge
    steps:
      - prepare_golang
      - run:
          name: Run unit tests
          command: make run-coverage

  race:
    docker:
      - image: cimg/go:1.15.7
    resource_class: xlarge
    steps:
      - prepare_golang
      - run:
          name: Run unit tests (race)
          command: make race

  integration:
    machine: true
    resource_class: xlarge
    steps:
      - run:
          name: Uninstall Go
          command: sudo rm -rvf /usr/local/go/
      - go/install:
          version: 1.15.7
      - prepare_golang
      - run:
          name: Integration tests
          command: make run-integration

  push-orchestrate-image:
    docker:
      - image: cimg/base:2020.01
    resource_class: large
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - prepare_docker
      - docker_build_dev
      - run:
          name: Deploy image in dev repository
          command: |
            docker push ${DOCKER_REGISTRY_DEV_REPO}/orchestrate:${CIRCLE_SHA1:0:7}

  push-orchestrate-e2e-image:
    docker:
      - image: cimg/base:2020.01
    resource_class: large
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - prepare_docker
      - docker_build_e2e_dev
      - run:
          name: Deploy e2e image in dev repository
          command: |
            docker push ${DOCKER_REGISTRY_DEV_REPO}/orchestrate-e2e:${CIRCLE_SHA1:0:7}

  deploy-qa:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: Deploy QA environment
          command: >-
            ORCHESTRATE_NAMESPACE=qa
            ORCHESTRATE_TAG=${CIRCLE_SHA1:0:7}
            ORCHESTRATE_REPOSITORY=${DOCKER_REGISTRY_DEV_REPO}/orchestrate
            ENVIRONMENT_VALUES=qa
            make deploy-remote-env

  run-e2e:
    docker:
      - image: cimg/go:1.15.8-node
    resource_class: large
    steps:
      - prepare_golang
      - prepare_e2e
      - run:
          name: Running e2e
          environment:
            CUCUMBER_OUTPUTPATH: "./scripts/report/report.json"
            CUCUMBER_OUTPUT: "./report.html"
            CUCUMBER_INPUT: "./report.json"
            CUCUMBER_PATHS: "./tests/features"
            ARTIFACTS_PATH: "./tests/artifacts"
            CUCUMBER_FORMAT: "cucumber"
            CUCUMBER_STEPS_TIMEOUT: "1m"
            CUCUMBER_CONCURRENCY: "5"
            KAFKA_CONSUMER_GROUP_NAME: "e2e"
            LOG_LEVEL: "INFO"
          command: |
            set +e
            METADATA_TAG=${CIRCLE_TAG}
            METADATA_BRANCH=${CIRCLE_BRANCH}
            METADATA_COMMIT=${CIRCLE_SHA1}
            METADATA_OS=${CIRCLE_BUILD_IMAGE}
            METADATA_RUNNER=${CIRCLE_BUILD_URL}
            METADATA_RUNNER_ID=${CIRCLE_BUILD_NUM}
            METADATA_RUNNER_VERSION=${CI_RUNNER_REVISION}
            ./build/bin/test e2e
            exitCode=$(echo $?)
            cd ./scripts/report
            npm install
            npm start
            exit $exitCode
      - store_artifacts:
          path: ./scripts/report/report.html
          destination: report.html

  run-stress:
    docker:
      - image: cimg/go:1.15.8
    resource_class: large
    steps:
      - prepare_golang
      - prepare_e2e
      - run:
          name: Running stress
          environment:
            ARTIFACTS_PATH: "./tests/artifacts"
            STRESS_CONCURRENCY: "10"
            STRESS_ITERATIONS: "500"
            STRESS_TIMEOUT: "10m"
            KAFKA_CONSUMER_GROUP_NAME: "stress"
          command: ./build/bin/test stress

  release-latest:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - prepare_docker
      - run:
          name: Release latest
          command: |
            docker pull ${DOCKER_REGISTRY_DEV_REPO}/orchestrate:${CIRCLE_SHA1:0:7}
            docker tag ${DOCKER_REGISTRY_DEV_REPO}/orchestrate:${CIRCLE_SHA1:0:7} ${DOCKER_REGISTRY_REPO}/orchestrate:latest
            docker push ${DOCKER_REGISTRY_REPO}/orchestrate:latest

  release-tag:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - prepare_docker
      - run:
          name: Release tagged version
          command: |
            docker pull ${DOCKER_REGISTRY_DEV_REPO}/orchestrate:${CIRCLE_SHA1:0:7}
            docker tag ${DOCKER_REGISTRY_DEV_REPO}/orchestrate:${CIRCLE_SHA1:0:7} ${DOCKER_REGISTRY_REPO}/orchestrate:${CIRCLE_TAG}
            docker push ${DOCKER_REGISTRY_REPO}/orchestrate:${CIRCLE_TAG}
            docker pull ${DOCKER_REGISTRY_DEV_REPO}/orchestrate-e2e:${CIRCLE_SHA1:0:7}
            docker tag ${DOCKER_REGISTRY_DEV_REPO}/orchestrate-e2e:${CIRCLE_SHA1:0:7} ${DOCKER_REGISTRY_REPO}/orchestrate-e2e:${CIRCLE_TAG}
            docker push ${DOCKER_REGISTRY_REPO}/orchestrate-e2e:${CIRCLE_TAG}

  deploy-staging:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: Deploy staging environment
          command: >-
            ORCHESTRATE_NAMESPACE=staging-${CIRCLE_TAG}
            ORCHESTRATE_TAG=${CIRCLE_TAG}
            ORCHESTRATE_REPOSITORY=${DOCKER_REGISTRY_REPO}/orchestrate
            ENVIRONMENT_VALUES=staging
            make deploy-remote-env

workflows:
  version: 2
  default:
    jobs:
      - lint
      - gobuild
      - test
      - race
      - integration
      - push-orchestrate-image:
          filters:
            branches:
              only: master
            tags:
              only: /^v.*/
          requires:
            - lint
            - gobuild
            - test
            - race
            - integration
      - push-orchestrate-e2e-image:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
          requires:
            - lint
            - gobuild
            - test
            - race
            - integration
      - deploy-qa:
          filters:
            branches:
              only: master
            tags:
              only: /^v.*/
          requires:
            - push-orchestrate-image
      - run-e2e:
          filters:
            branches:
              only: master
            tags:
              only: /^v.*/
          requires:
            - deploy-qa
      - run-stress:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
          requires:
            - run-e2e
      - release-latest:
          filters:
            branches:
              only: master
            tags:
              ignore: /.*/
          requires:
            - run-e2e
      - wait-for-approval:
          type: approval
          requires:
            - run-e2e
            - run-stress
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - release-tag:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
          requires:
            - wait-for-approval
      - deploy-staging:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
          requires:
            - release-tag
