// Code generated by MockGen. DO NOT EDIT.
// Source: push_notification.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	entities "github.com/consensys/orchestrate/src/entities"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockNotifier is a mock of Notifier interface
type MockNotifier struct {
	ctrl     *gomock.Controller
	recorder *MockNotifierMockRecorder
}

// MockNotifierMockRecorder is the mock recorder for MockNotifier
type MockNotifierMockRecorder struct {
	mock *MockNotifier
}

// NewMockNotifier creates a new mock instance
func NewMockNotifier(ctrl *gomock.Controller) *MockNotifier {
	mock := &MockNotifier{ctrl: ctrl}
	mock.recorder = &MockNotifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockNotifier) EXPECT() *MockNotifierMockRecorder {
	return m.recorder
}

// SendTxResponse mocks base method
func (m *MockNotifier) SendTxResponse(ctx context.Context, eventStream *entities.EventStream, job *entities.Job, errStr string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendTxResponse", ctx, eventStream, job, errStr)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendTxResponse indicates an expected call of SendTxResponse
func (mr *MockNotifierMockRecorder) SendTxResponse(ctx, eventStream, job, errStr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendTxResponse", reflect.TypeOf((*MockNotifier)(nil).SendTxResponse), ctx, eventStream, job, errStr)
}
