// Code generated by MockGen. DO NOT EDIT.
// Source: listener.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	events "github.com/consensys/orchestrate/src/chain-listener/service/listener/events"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockChainListener is a mock of ChainListener interface
type MockChainListener struct {
	ctrl     *gomock.Controller
	recorder *MockChainListenerMockRecorder
}

// MockChainListenerMockRecorder is the mock recorder for MockChainListener
type MockChainListenerMockRecorder struct {
	mock *MockChainListener
}

// NewMockChainListener creates a new mock instance
func NewMockChainListener(ctrl *gomock.Controller) *MockChainListener {
	mock := &MockChainListener{ctrl: ctrl}
	mock.recorder = &MockChainListenerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockChainListener) EXPECT() *MockChainListenerMockRecorder {
	return m.recorder
}

// Start mocks base method
func (m *MockChainListener) Run(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start
func (mr *MockChainListenerMockRecorder) Run(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockChainListener)(nil).Run), arg0)
}

// Close mocks base method
func (m *MockChainListener) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close
func (mr *MockChainListenerMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockChainListener)(nil).Close))
}

// Subscribe mocks base method
func (m *MockChainListener) Subscribe(arg0 chan *events.Chain) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", arg0)
	ret0, _ := ret[0].(string)
	return ret0
}

// Subscribe indicates an expected call of Subscribe
func (mr *MockChainListenerMockRecorder) Subscribe(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockChainListener)(nil).Subscribe), arg0)
}

// Unsubscribe mocks base method
func (m *MockChainListener) Unsubscribe(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unsubscribe", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unsubscribe indicates an expected call of Unsubscribe
func (mr *MockChainListenerMockRecorder) Unsubscribe(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unsubscribe", reflect.TypeOf((*MockChainListener)(nil).Unsubscribe), arg0)
}

// MockChainBlockListener is a mock of ChainBlockListener interface
type MockChainBlockListener struct {
	ctrl     *gomock.Controller
	recorder *MockChainBlockListenerMockRecorder
}

// MockChainBlockListenerMockRecorder is the mock recorder for MockChainBlockListener
type MockChainBlockListenerMockRecorder struct {
	mock *MockChainBlockListener
}

// NewMockChainBlockListener creates a new mock instance
func NewMockChainBlockListener(ctrl *gomock.Controller) *MockChainBlockListener {
	mock := &MockChainBlockListener{ctrl: ctrl}
	mock.recorder = &MockChainBlockListenerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockChainBlockListener) EXPECT() *MockChainBlockListenerMockRecorder {
	return m.recorder
}

// Start mocks base method
func (m *MockChainBlockListener) Run(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start
func (mr *MockChainBlockListenerMockRecorder) Run(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockChainBlockListener)(nil).Run), ctx)
}

// Close mocks base method
func (m *MockChainBlockListener) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close
func (mr *MockChainBlockListenerMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockChainBlockListener)(nil).Close))
}

// MockChainPendingJobsListener is a mock of ChainPendingJobsListener interface
type MockChainPendingJobsListener struct {
	ctrl     *gomock.Controller
	recorder *MockChainPendingJobsListenerMockRecorder
}

// MockChainPendingJobsListenerMockRecorder is the mock recorder for MockChainPendingJobsListener
type MockChainPendingJobsListenerMockRecorder struct {
	mock *MockChainPendingJobsListener
}

// NewMockChainPendingJobsListener creates a new mock instance
func NewMockChainPendingJobsListener(ctrl *gomock.Controller) *MockChainPendingJobsListener {
	mock := &MockChainPendingJobsListener{ctrl: ctrl}
	mock.recorder = &MockChainPendingJobsListenerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockChainPendingJobsListener) EXPECT() *MockChainPendingJobsListenerMockRecorder {
	return m.recorder
}

// Start mocks base method
func (m *MockChainPendingJobsListener) Run(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start
func (mr *MockChainPendingJobsListenerMockRecorder) Run(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockChainPendingJobsListener)(nil).Run), arg0)
}

// Close mocks base method
func (m *MockChainPendingJobsListener) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close
func (mr *MockChainPendingJobsListenerMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockChainPendingJobsListener)(nil).Close))
}
