// Code generated by MockGen. DO NOT EDIT.
// Source: sessions.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	entities "github.com/consensys/orchestrate/src/entities"
	sessions "github.com/consensys/orchestrate/src/tx-listener/tx-listener/sessions"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockChainSessionManager is a mock of ChainSessionManager interface
type MockChainSessionManager struct {
	ctrl     *gomock.Controller
	recorder *MockChainSessionManagerMockRecorder
}

// MockChainSessionManagerMockRecorder is the mock recorder for MockChainSessionManager
type MockChainSessionManagerMockRecorder struct {
	mock *MockChainSessionManager
}

// NewMockChainSessionManager creates a new mock instance
func NewMockChainSessionManager(ctrl *gomock.Controller) *MockChainSessionManager {
	mock := &MockChainSessionManager{ctrl: ctrl}
	mock.recorder = &MockChainSessionManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockChainSessionManager) EXPECT() *MockChainSessionManagerMockRecorder {
	return m.recorder
}

// StartSession mocks base method
func (m *MockChainSessionManager) StartSession(ctx context.Context, chainUUID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartSession", ctx, chainUUID)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartSession indicates an expected call of StartSession
func (mr *MockChainSessionManagerMockRecorder) StartSession(ctx, chainUUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartSession", reflect.TypeOf((*MockChainSessionManager)(nil).StartSession), ctx, chainUUID)
}

// MockRetryJobSessionManager is a mock of RetryJobSessionManager interface
type MockRetryJobSessionManager struct {
	ctrl     *gomock.Controller
	recorder *MockRetryJobSessionManagerMockRecorder
}

// MockRetryJobSessionManagerMockRecorder is the mock recorder for MockRetryJobSessionManager
type MockRetryJobSessionManagerMockRecorder struct {
	mock *MockRetryJobSessionManager
}

// NewMockRetryJobSessionManager creates a new mock instance
func NewMockRetryJobSessionManager(ctrl *gomock.Controller) *MockRetryJobSessionManager {
	mock := &MockRetryJobSessionManager{ctrl: ctrl}
	mock.recorder = &MockRetryJobSessionManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRetryJobSessionManager) EXPECT() *MockRetryJobSessionManagerMockRecorder {
	return m.recorder
}

// StartSession mocks base method
func (m *MockRetryJobSessionManager) StartSession(ctx context.Context, job *entities.Job) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartSession", ctx, job)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartSession indicates an expected call of StartSession
func (mr *MockRetryJobSessionManagerMockRecorder) StartSession(ctx, job interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartSession", reflect.TypeOf((*MockRetryJobSessionManager)(nil).StartSession), ctx, job)
}

// MockSessionManagers is a mock of SessionManagers interface
type MockSessionManagers struct {
	ctrl     *gomock.Controller
	recorder *MockSessionManagersMockRecorder
}

// MockSessionManagersMockRecorder is the mock recorder for MockSessionManagers
type MockSessionManagersMockRecorder struct {
	mock *MockSessionManagers
}

// NewMockSessionManagers creates a new mock instance
func NewMockSessionManagers(ctrl *gomock.Controller) *MockSessionManagers {
	mock := &MockSessionManagers{ctrl: ctrl}
	mock.recorder = &MockSessionManagersMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockSessionManagers) EXPECT() *MockSessionManagersMockRecorder {
	return m.recorder
}

// ChainSessionManager mocks base method
func (m *MockSessionManagers) ChainSessionManager() sessions.ChainSessionManager {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChainSessionManager")
	ret0, _ := ret[0].(sessions.ChainSessionManager)
	return ret0
}

// ChainSessionManager indicates an expected call of ChainSessionManager
func (mr *MockSessionManagersMockRecorder) ChainSessionManager() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChainSessionManager", reflect.TypeOf((*MockSessionManagers)(nil).ChainSessionManager))
}

// RetryJobSessionManager mocks base method
func (m *MockSessionManagers) RetryJobSessionManager() sessions.RetryJobSessionManager {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetryJobSessionManager")
	ret0, _ := ret[0].(sessions.RetryJobSessionManager)
	return ret0
}

// RetryJobSessionManager indicates an expected call of RetryJobSessionManager
func (mr *MockSessionManagersMockRecorder) RetryJobSessionManager() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetryJobSessionManager", reflect.TypeOf((*MockSessionManagers)(nil).RetryJobSessionManager))
}
